CREATE TABLE device (
	ID INTEGER NOT NULL,
	shard INTEGER,
	IP TEXT NOT NULL,
	CONSTRAINT PK_DEVICE PRIMARY KEY (ID, shard)
);

CREATE TABLE dataD(
	whenD LONG NOT NULL,
	whoMachine INTEGER NOT NULL,
	whoShard INTEGER NOT NULL,
	typeD TEXT NOT NULL,
	valueD REAL NOT NULL,
	net TEXT NOT NULL,
	CONSTRAINT PK_DataD PRIMARY KEY (whenD, whoMachine, whoShard),
	CONSTRAINT FK_DatD_Device FOREIGN KEY (whoMachine) REFERENCES Device(ID),
	CONSTRAINT FK_DatD_Device2 FOREIGN KEY (whoShard) REFERENCES Device(shard)
);